# Equipo No.11

### Grupo:      003
             Lunes: 6pm~9pm
### Integrantes: 
             GARZA AMAYA HECTOR YAIR
             SAUCEDO OROZCO ALBERTO
             GONZALEZ CURIEL SEBASTIAN
             ALSINA RODRIGUEZ BRANDON DANIEL

## FIFA 19 (https://www.kaggle.com/karangadiya/fifa19)

### Importación de Librerias

In [1]:
import pandas as pd
import numpy as np
import json
import zipfile as zp

### Carga de bases de datos

In [2]:
fifa = pd.read_csv("C:\\Users\\alber\\OneDrive - uanl.edu.mx\\UNIVERSIDAD\\UNIVERSIDAD\\TAREAS\\Mineria de Datos\\Practica 1.Limpieza csv\\archive (1)\data.csv")
covid = pd.read_csv("C:\\Users\\alber\\OneDrive - uanl.edu.mx\\UNIVERSIDAD\\UNIVERSIDAD\\TAREAS\\Mineria de Datos\\Practica 1.Limpieza csv\\archive\\country_wise_latest.csv")

### Visualización de datos e información (FIFA)

In [3]:
fifa.head(5)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [4]:
fifa.tail(5)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

### Descripción de columnas

In [5]:
#Revisar la cantidad de filas y columnas
fifa.shape

(18207, 89)

In [6]:
#Mostrar nombres de las columnas de la base de datos
fifa.columns
#Tenemos muchas columnas no relevantes

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [7]:
#Clasificación de datos por columna
fifa.dtypes

Unnamed: 0          int64
ID                  int64
Name               object
Age                 int64
Photo              object
                   ...
GKHandling        float64
GKKicking         float64
GKPositioning     float64
GKReflexes        float64
Release Clause     object
Length: 89, dtype: object

In [8]:
#Se revisa si la base de datos contiene valores nulos y se hace la suma por columna
fifa.isnull().sum()

Unnamed: 0           0
ID                   0
Name                 0
Age                  0
Photo                0
                  ...
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 89, dtype: int64

### Guardar datos con agrupaciones

In [9]:
#Se eliminan las columnas que contengan celdas vacias
fifa_lleno= fifa.dropna(axis=1)
#Se guarda el cambio en otro .csv
fifa_lleno.to_csv

<bound method NDFrame.to_csv of        Unnamed: 0      ID                Name  Age  \
0               0  158023            L. Messi   31
1               1   20801   Cristiano Ronaldo   33
2               2  190871           Neymar Jr   26
3               3  193080              De Gea   27
4               4  192985        K. De Bruyne   27
...           ...     ...                 ...  ...
18202       18202  238813        J. Lundstram   19
18203       18203  243165  N. Christoffersson   19
18204       18204  241638           B. Worman   16
18205       18205  246268      D. Walker-Rice   17
18206       18206  246269           G. Nugent   16

                                                Photo Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium
...                                               ...         ...
18202  https://cdn.sofifa.org/players/4/19/238813.png     England
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden
18204  https://cdn.sofifa.org/players/4/19/241638.png     England
18205  https://cdn.sofifa.org/players/4/19/246268.png     England
18206  https://cdn.sofifa.org/players/4/19/246269.png     England

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.org/flags/52.png       94         94
1      https://cdn.sofifa.org/flags/38.png       94         94
2      https://cdn.sofifa.org/flags/54.png       92         93
3      https://cdn.sofifa.org/flags/45.png       91         93
4       https://cdn.sofifa.org/flags/7.png       91         92
...                                    ...      ...        ...
18202  https://cdn.sofifa.org/flags/14.png       47         65
18203  https://cdn.sofifa.org/flags/46.png       47         63
18204  https://cdn.sofifa.org/flags/14.png       47         67
18205  https://cdn.sofifa.org/flags/14.png       47         66
18206  https://cdn.sofifa.org/flags/14.png       46         66

                                            Club Logo    Value   Wage  Special
0        https://cdn.sofifa.org/teams/2/light/241.png  €110.5M  €565K     2202
1         https://cdn.sofifa.org/teams/2/light/45.png     €77M  €405K     2228
2         https://cdn.sofifa.org/teams/2/light/73.png  €118.5M  €290K     2143
3         https://cdn.sofifa.org/teams/2/light/11.png     €72M  €260K     1471
4         https://cdn.sofifa.org/teams/2/light/10.png    €102M  €355K     2281
...                                               ...      ...    ...      ...
18202    https://cdn.sofifa.org/teams/2/light/121.png     €60K    €1K     1307
18203    https://cdn.sofifa.org/teams/2/light/703.png     €60K    €1K     1098
18204   https://cdn.sofifa.org/teams/2/light/1944.png     €60K    €1K     1189
18205  https://cdn.sofifa.org/teams/2/light/15048.png     €60K    €1K     1228
18206  https://cdn.sofifa.org/teams/2/light/15048.png     €60K    €1K     1321

[18207 rows x 13 columns]>

In [10]:
#Verificar que haya funcionado la anterior eliminacion de columnas con valores nulos
fifa_lleno.isnull().any()

Unnamed: 0     False
ID             False
Name           False
Age            False
Photo          False
Nationality    False
Flag           False
Overall        False
Potential      False
Club Logo      False
Value          False
Wage           False
Special        False
dtype: bool

In [22]:
#Ultimos cambios a la nueva base de datos
fifa_lleno=fifa_lleno.rename(columns={'Overall':'Calification Overall'})
fifa_lleno=fifa_lleno.rename(columns={'Potential':'Calification Potential'})
fifa_lleno=fifa_lleno.drop('Special',axis=1)

In [23]:
fifa_lleno

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Calification Overall,Calification Potential,Club Logo,Value,Wage
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,https://cdn.sofifa.org/teams/2/light/241.png,€110.5M,€565K
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,https://cdn.sofifa.org/teams/2/light/45.png,€77M,€405K
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,https://cdn.sofifa.org/teams/2/light/73.png,€118.5M,€290K
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,https://cdn.sofifa.org/teams/2/light/11.png,€72M,€260K
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,https://cdn.sofifa.org/teams/2/light/10.png,€102M,€355K
...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,https://cdn.sofifa.org/teams/2/light/121.png,€60K,€1K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,https://cdn.sofifa.org/teams/2/light/703.png,€60K,€1K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,https://cdn.sofifa.org/teams/2/light/1944.png,€60K,€1K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,https://cdn.sofifa.org/teams/2/light/15048.png,€60K,€1K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,https://cdn.sofifa.org/teams/2/light/15048.png,€60K,€1K

## COVID-19 Dataset (https://www.kaggle.com/imdevskp/corona-virus-report)

### Visualización de datos e información (COVID)

In [13]:
covid.head(5)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [14]:
covid.tail(5)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [15]:
covid.shape

(187, 15)

In [16]:
#Las columnas de esta base de datos permanecera sin cambios por la relevancia de sus datos
covid.columns

Index(['Country/Region', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'New cases', 'New deaths', 'New recovered', 'Deaths / 100 Cases',
       'Recovered / 100 Cases', 'Deaths / 100 Recovered',
       'Confirmed last week', '1 week change', '1 week % increase',
       'WHO Region'],
      dtype='object')

In [17]:
#Se crea nueva agrupación para los paises con casos confirmados mayores a 10,000
covid_10000=covid[covid['Confirmed']>10000]
#Guardar la anterior agrupación en .csv
covid_10000.to_csv

<bound method NDFrame.to_csv of            Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0             Afghanistan      36263    1269      25198    9796        106
2                 Algeria      27973    1163      18837    7973        616
6               Argentina     167416    3059      72575   91782       4890
7                 Armenia      37390     711      26665   10014         73
8               Australia      15303     167       9311    5825        368
..                    ...        ...     ...        ...     ...        ...
176  United Arab Emirates      59177     345      52510    6322        264
177        United Kingdom     301708   45844       1437  254427        688
179            Uzbekistan      21209     121      11674    9414        678
180             Venezuela      15988     146       9959    5883        525
182    West Bank and Gaza      10621      78       3752    6791        152

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0            10             18                3.50                  69.49
2             8            749                4.16                  67.34
6           120           2057                1.83                  43.35
7             6            187                1.90                  71.32
8             6            137                1.09                  60.84
..          ...            ...                 ...                    ...
176           1            328                0.58                  88.73
177           7              3               15.19                   0.48
179           5            569                0.57                  55.04
180           4            213                0.91                  62.29
182           2              0                0.73                  35.33

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                      5.04                35526            737
2                      6.17                23691           4282
6                      4.21               130774          36642
7                      2.67                34981           2409
8                      1.79                12428           2875
..                      ...                  ...            ...
176                    0.66                57193           1984
177                 3190.26               296944           4764
179                    1.04                17149           4060
180                    1.47                12334           3654
182                    2.08                 8916           1705

     1 week % increase             WHO Region
0                 2.07  Eastern Mediterranean
2                18.07                 Africa
6                28.02               Americas
7                 6.89                 Europe
8                23.13        Western Pacific
..                 ...                    ...
176               3.47  Eastern Mediterranean
177               1.60                 Europe
179              23.67                 Europe
180              29.63               Americas
182              19.12  Eastern Mediterranean

[80 rows x 15 columns]>

In [18]:
covid_10000.shape

(80, 15)